export const projectsList = [
  { service: " Air Conditioning" },
  { service: "Clean Air Ducts and Vents" },
  { service: "Heating &amp; Furnace Systems" },
  { service: "Install a Central Air Conditioning System" },
  { service: "Install a Central Air Conditioning System - For Business" },
  { service: "Install a Geothermal Heating or Cooling System" },
  { service: "Install a Radiant Floor Heating System" },
  { service: "Install a Tankless Water Heater System" },
  { service: "Install a Window Air Conditioning Unit" },
  { service: "Install a Window Air Conditioning Unit - For Business" },
  { service: "Install an Electrical Baseboard or Wall Heater" },
  { service: "Install or Completely Replace PVC Gutters" },
  { service: "Install or Replace a Boiler or Radiator Heating System" },
  { service: "Install or Replace a Central Air Cleaner" },
  { service: "Install or Replace a Central Humidifier" },
  { service: "Install or Replace a Heat Pump" },
  { service: "Install or Replace a Swamp Cooler" },
  { service: "Install or Replace a Thermostat" },
  { service: "Install or Replace a Vinyl or PVC Fence" },
  { service: "Install or Replace Ductwork" },
  { service: "Install or Replace Furnace or Forced Air Heating System" },
  { service: "Install or Replace Swimming Pool Heaters" },
  { service: "Install Radiant Panel Heating Units" },
  { service: "Relocate or Service a Window Air Conditioning Unit" },
  {
    service:
      "Relocate or Service a Window Air Conditioning Unit - For Business",
  },
  { service: "Repair a Tankless Water Heater System" },
  { service: "Repair an Electrical Baseboard or Wall Heater" },
  { service: "Repair or Partially Replace a PVC or Plastic Fence" },
  { service: "Repair or Replace Section of PVC Gutters" },
  { service: "Repair or Reprogram a Thermostat" },
  { service: "Repair or Service a Boiler or Radiator Heating System" },
  { service: "Repair or Service a Central Air Cleaner" },
  { service: "Repair or Service a Central Air Conditioning System" },
  {
    service:
      "Repair or Service a Central Air Conditioning System - For Business",
  },
  { service: "Repair or Service a Central Humidifier" },
  { service: "Repair or Service a Heat Pump" },
  { service: "Repair or Service a Radiant Floor Heating System" },
  { service: "Repair or Service a Swamp Cooler" },
  { service: "Repair or Service a Water Heater" },
  { service: "Repair or Service Furnace or Forced Air Heating System" },
  { service: "Repair Radiant Panel Heating Units" },
  { service: "Service a Geothermal Heating or Cooling System" },
]
